name: Version Up

on:
  push:
    branches: [main]

jobs:
  auto-version-up:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
        with:
          ref: main
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "pnpm"
      - name: Auto version update
        run: |
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
          pnpm install --frozen-lockfile
          pnpm lerna:version:up
